/* ============================================================
   data.js — curated static question banks (verbal, anglais, aero)
   Each item: { id, sub, prompt, options[], answer, explain }
   `answer` is the exact text of the correct option (order is
   shuffled at render time so the correct slot is never fixed).
   ============================================================ */

const VERBAL_BANK = [
  // --- Synonymes ---
  { id: "v1", sub: "synonyme", prompt: "LACONIQUE se rapproche le plus de :", options: ["Bavard", "Concis", "Confus", "Bruyant"], answer: "Concis" },
  { id: "v2", sub: "synonyme", prompt: "PERSPICACE se rapproche le plus de :", options: ["Lucide", "Distrait", "Maladroit", "Hésitant"], answer: "Lucide" },
  { id: "v3", sub: "synonyme", prompt: "VOLUBILE se rapproche le plus de :", options: ["Taciturne", "Loquace", "Discret", "Timide"], answer: "Loquace" },
  { id: "v4", sub: "synonyme", prompt: "OPULENT se rapproche le plus de :", options: ["Misérable", "Fastueux", "Modeste", "Austère"], answer: "Fastueux" },
  { id: "v5", sub: "synonyme", prompt: "INTRÉPIDE se rapproche le plus de :", options: ["Craintif", "Audacieux", "Prudent", "Réservé"], answer: "Audacieux" },
  { id: "v6", sub: "synonyme", prompt: "ÉPHÉMÈRE se rapproche le plus de :", options: ["Durable", "Passager", "Éternel", "Stable"], answer: "Passager" },
  { id: "v7", sub: "synonyme", prompt: "CANDIDE se rapproche le plus de :", options: ["Rusé", "Naïf", "Cynique", "Méfiant"], answer: "Naïf" },
  { id: "v8", sub: "synonyme", prompt: "PROLIXE se rapproche le plus de :", options: ["Concis", "Verbeux", "Muet", "Sobre"], answer: "Verbeux" },
  { id: "v9", sub: "synonyme", prompt: "TENACE se rapproche le plus de :", options: ["Obstiné", "Versatile", "Indifférent", "Las"], answer: "Obstiné" },
  { id: "v10", sub: "synonyme", prompt: "FUTILE se rapproche le plus de :", options: ["Essentiel", "Insignifiant", "Grave", "Urgent"], answer: "Insignifiant" },
  { id: "v11", sub: "synonyme", prompt: "LUCIDE se rapproche le plus de :", options: ["Confus", "Clairvoyant", "Naïf", "Distrait"], answer: "Clairvoyant" },
  { id: "v12", sub: "synonyme", prompt: "AUSTÈRE se rapproche le plus de :", options: ["Rigide", "Permissif", "Joyeux", "Frivole"], answer: "Rigide" },
  // --- Antonymes ---
  { id: "v13", sub: "antonyme", prompt: "Le contraire de GÉNÉREUX est :", options: ["Prodigue", "Avare", "Charitable", "Altruiste"], answer: "Avare" },
  { id: "v14", sub: "antonyme", prompt: "Le contraire de TIMIDE est :", options: ["Réservé", "Audacieux", "Craintif", "Discret"], answer: "Audacieux" },
  { id: "v15", sub: "antonyme", prompt: "Le contraire d'ABONDANT est :", options: ["Rare", "Copieux", "Nombreux", "Foisonnant"], answer: "Rare" },
  { id: "v16", sub: "antonyme", prompt: "Le contraire de RIGOUREUX est :", options: ["Précis", "Laxiste", "Strict", "Exigeant"], answer: "Laxiste" },
  { id: "v17", sub: "antonyme", prompt: "Le contraire d'OPTIMISTE est :", options: ["Confiant", "Pessimiste", "Enthousiaste", "Positif"], answer: "Pessimiste" },
  { id: "v18", sub: "antonyme", prompt: "Le contraire de TRANQUILLE est :", options: ["Paisible", "Agité", "Calme", "Serein"], answer: "Agité" },
  { id: "v19", sub: "antonyme", prompt: "Le contraire d'HUMBLE est :", options: ["Modeste", "Arrogant", "Discret", "Simple"], answer: "Arrogant" },
  { id: "v20", sub: "antonyme", prompt: "Le contraire de PRÉCOCE est :", options: ["Avancé", "Tardif", "Rapide", "Doué"], answer: "Tardif" },
  { id: "v21", sub: "antonyme", prompt: "Le contraire de CLÉMENT est :", options: ["Indulgent", "Sévère", "Doux", "Bienveillant"], answer: "Sévère" },
  { id: "v22", sub: "antonyme", prompt: "Le contraire de SÉDENTAIRE est :", options: ["Casanier", "Nomade", "Immobile", "Stable"], answer: "Nomade" },
  { id: "v23", sub: "antonyme", prompt: "Le contraire de LUCRATIF est :", options: ["Rentable", "Déficitaire", "Profitable", "Fructueux"], answer: "Déficitaire" },
  { id: "v24", sub: "antonyme", prompt: "Le contraire de VOLONTAIRE est :", options: ["Déterminé", "Réticent", "Motivé", "Résolu"], answer: "Réticent" },
  // --- Analogies ---
  { id: "v25", sub: "analogie", prompt: "Oiseau est à Nid ce que Abeille est à :", options: ["Fleur", "Ruche", "Miel", "Ciel"], answer: "Ruche" },
  { id: "v26", sub: "analogie", prompt: "Médecin est à Hôpital ce que Enseignant est à :", options: ["Livre", "École", "Élève", "Craie"], answer: "École" },
  { id: "v27", sub: "analogie", prompt: "Marteau est à Clou ce que Tournevis est à :", options: ["Bois", "Vis", "Perceuse", "Boulon"], answer: "Vis" },
  { id: "v28", sub: "analogie", prompt: "Pilote est à Avion ce que Capitaine est à :", options: ["Voiture", "Navire", "Train", "Hangar"], answer: "Navire" },
  { id: "v29", sub: "analogie", prompt: "Graine est à Arbre ce que Œuf est à :", options: ["Nid", "Poule", "Oiseau", "Coquille"], answer: "Oiseau" },
  { id: "v30", sub: "analogie", prompt: "Thermomètre est à Température ce que Baromètre est à :", options: ["Altitude", "Pression", "Vent", "Humidité"], answer: "Pression" },
  { id: "v31", sub: "analogie", prompt: "Livre est à Chapitre ce que Année est à :", options: ["Jour", "Mois", "Saison", "Semaine"], answer: "Mois" },
  { id: "v32", sub: "analogie", prompt: "Faim est à Manger ce que Soif est à :", options: ["Cuisiner", "Boire", "Verre", "Eau"], answer: "Boire" },
  { id: "v33", sub: "analogie", prompt: "Peintre est à Toile ce que Sculpteur est à :", options: ["Pinceau", "Marbre", "Musée", "Ciseau"], answer: "Marbre" },
  { id: "v34", sub: "analogie", prompt: "Nuage est à Pluie ce que Étincelle est à :", options: ["Fumée", "Feu", "Chaleur", "Cendre"], answer: "Feu" },
  { id: "v35", sub: "analogie", prompt: "Clé est à Serrure ce que Code est à :", options: ["Ordinateur", "Coffre-fort", "Mot de passe", "Verrou"], answer: "Coffre-fort" },
  { id: "v36", sub: "analogie", prompt: "Aile est à Avion ce que Nageoire est à :", options: ["Requin", "Océan", "Poisson", "Eau"], answer: "Poisson" },
];

const ANGLAIS_BANK = [
  // --- Vocabulary ---
  { id: "e1", sub: "vocabulaire", prompt: "\"Meticulous\" means:", options: ["Careless", "Very careful and precise", "Fast", "Confused"], answer: "Very careful and precise" },
  { id: "e2", sub: "vocabulaire", prompt: "\"Reluctant\" means:", options: ["Eager", "Unwilling", "Forced", "Confident"], answer: "Unwilling" },
  { id: "e3", sub: "vocabulaire", prompt: "\"Concise\" means:", options: ["Wordy", "Brief and clear", "Vague", "Loud"], answer: "Brief and clear" },
  { id: "e4", sub: "vocabulaire", prompt: "\"Diligent\" means:", options: ["Lazy", "Hardworking", "Careless", "Slow"], answer: "Hardworking" },
  { id: "e5", sub: "vocabulaire", prompt: "\"Ambiguous\" means:", options: ["Clear", "Open to more than one interpretation", "Simple", "Certain"], answer: "Open to more than one interpretation" },
  { id: "e6", sub: "vocabulaire", prompt: "\"Feasible\" means:", options: ["Impossible", "Doable", "Expensive", "Risky"], answer: "Doable" },
  { id: "e7", sub: "vocabulaire", prompt: "\"Adjacent\" means:", options: ["Far away", "Next to", "Above", "Inside"], answer: "Next to" },
  { id: "e8", sub: "vocabulaire", prompt: "\"Sturdy\" means:", options: ["Fragile", "Strong and well-built", "Light", "Old"], answer: "Strong and well-built" },
  { id: "e9", sub: "vocabulaire", prompt: "\"Vigilant\" means:", options: ["Careless", "Watchful", "Tired", "Calm"], answer: "Watchful" },
  { id: "e10", sub: "vocabulaire", prompt: "\"Abrupt\" means:", options: ["Gradual", "Sudden", "Smooth", "Delayed"], answer: "Sudden" },
  { id: "e11", sub: "vocabulaire", prompt: "\"Persistent\" means:", options: ["Giving up easily", "Continuing firmly", "Occasional", "Hesitant"], answer: "Continuing firmly" },
  { id: "e12", sub: "vocabulaire", prompt: "\"Reliable\" means:", options: ["Untrustworthy", "Dependable", "Unstable", "Unclear"], answer: "Dependable" },
  // --- Grammar ---
  { id: "e13", sub: "grammaire", prompt: "\"If the weather ___ bad, the flight will be delayed.\"", options: ["is", "was", "were", "be"], answer: "is" },
  { id: "e14", sub: "grammaire", prompt: "\"By the time we land, we ___ flying for six hours.\"", options: ["will have been", "will be", "have been", "are"], answer: "will have been" },
  { id: "e15", sub: "grammaire", prompt: "\"She is the pilot ___ trained in Toulouse.\"", options: ["who", "which", "whom", "whose"], answer: "who" },
  { id: "e16", sub: "grammaire", prompt: "\"The captain asked the crew ___ the doors.\"", options: ["to close", "closing", "closed", "close"], answer: "to close" },
  { id: "e17", sub: "grammaire", prompt: "\"Neither the co-pilot nor the captain ___ available now.\"", options: ["are", "is", "were", "have"], answer: "is" },
  { id: "e18", sub: "grammaire", prompt: "\"This is the most turbulent flight I ___ ever taken.\"", options: ["have", "has", "had", "having"], answer: "have" },
  { id: "e19", sub: "grammaire", prompt: "\"The plane took off ___ the storm warning.\"", options: ["despite", "although", "because", "unless"], answer: "despite" },
  { id: "e20", sub: "grammaire", prompt: "\"___ you finished the checklist yet?\"", options: ["Did", "Have", "Do", "Was"], answer: "Have" },
  { id: "e21", sub: "grammaire", prompt: "\"He would have called ___ he had signal.\"", options: ["if", "unless", "when", "so"], answer: "if" },
  { id: "e22", sub: "grammaire", prompt: "\"The runway ___ currently being repaved.\"", options: ["is", "are", "was", "were"], answer: "is" },
  { id: "e23", sub: "grammaire", prompt: "\"I look forward ___ from you soon.\"", options: ["to hear", "to hearing", "hearing", "hear"], answer: "to hearing" },
  { id: "e24", sub: "grammaire", prompt: "\"Passengers must remain seated ___ the seatbelt sign is on.\"", options: ["during", "while", "for", "since"], answer: "while" },
  // --- Aviation English ---
  { id: "e25", sub: "aviation", prompt: "What does \"ETA\" stand for?", options: ["Estimated Time of Arrival", "Exact Time Available", "Extended Travel Advisory", "Emergency Transit Alert"], answer: "Estimated Time of Arrival" },
  { id: "e26", sub: "aviation", prompt: "\"Mayday\" is used to signal:", options: ["A minor delay", "A life-threatening emergency", "A request for weather", "A routine check"], answer: "A life-threatening emergency" },
  { id: "e27", sub: "aviation", prompt: "\"Roger\" in radio communication means:", options: ["I disagree", "Message received and understood", "Please repeat", "Goodbye"], answer: "Message received and understood" },
  { id: "e28", sub: "aviation", prompt: "\"Squawk\" refers to:", options: ["A bird strike", "A transponder code", "A type of turbulence", "An engine noise"], answer: "A transponder code" },
  { id: "e29", sub: "aviation", prompt: "A \"holding pattern\" means the aircraft is:", options: ["Landing immediately", "Circling while waiting for clearance", "Taxiing to the gate", "Climbing to cruise altitude"], answer: "Circling while waiting for clearance" },
  { id: "e30", sub: "aviation", prompt: "\"Wilco\" means:", options: ["Will comply", "Will cancel", "Weather is clear", "Wait, correcting"], answer: "Will comply" },
  { id: "e31", sub: "aviation", prompt: "A \"go-around\" means the pilot:", options: ["Lands normally", "Aborts the landing and climbs away", "Taxis back", "Shuts down engines"], answer: "Aborts the landing and climbs away" },
  { id: "e32", sub: "aviation", prompt: "\"Turbulence\" refers to:", options: ["Smooth air", "Irregular air movement causing bumps", "A radio signal", "A fuel type"], answer: "Irregular air movement causing bumps" },
  { id: "e33", sub: "aviation", prompt: "A \"runway incursion\" means:", options: ["An unauthorized presence on a runway", "A scheduled landing", "A fuel stop", "A weather delay"], answer: "An unauthorized presence on a runway" },
  { id: "e34", sub: "aviation", prompt: "\"Ceiling\" in aviation weather means:", options: ["The aircraft's maximum altitude", "The height of the lowest cloud layer", "The cabin roof", "The cruising speed"], answer: "The height of the lowest cloud layer" },
  { id: "e35", sub: "aviation", prompt: "\"De-icing\" is done to:", options: ["Cool the engines", "Remove ice from surfaces before flight", "Increase cabin pressure", "Refuel the aircraft"], answer: "Remove ice from surfaces before flight" },
  { id: "e36", sub: "aviation", prompt: "\"Final approach\" refers to:", options: ["The last leg before landing", "The first climb after takeoff", "Taxiing to the runway", "Parking at the gate"], answer: "The last leg before landing" },
];

const AERO_BANK = [
  { id: "a1", sub: "principes", prompt: "La portance d'une aile provient principalement de :", options: ["La différence de pression entre l'extrados et l'intrados", "La poussée des réacteurs", "Le poids de l'appareil", "La force centrifuge"], answer: "La différence de pression entre l'extrados et l'intrados" },
  { id: "a2", sub: "réglementation", prompt: "Le sigle OACI signifie :", options: ["Organisation de l'Aviation Civile Internationale", "Office Aérien de Coordination Interne", "Organisme Aéronautique Civil International", "Organisation Aérienne et Commerciale Internationale"], answer: "Organisation de l'Aviation Civile Internationale" },
  { id: "a3", sub: "histoire", prompt: "Le premier vol motorisé et contrôlé de l'histoire a été réalisé par :", options: ["Clément Ader", "Les frères Wright", "Louis Blériot", "Otto Lilienthal"], answer: "Les frères Wright" },
  { id: "a4", sub: "instruments", prompt: "Que mesure un altimètre ?", options: ["La vitesse de l'avion", "L'altitude", "La pression au sol", "L'inclinaison de l'appareil"], answer: "L'altitude" },
  { id: "a5", sub: "principes", prompt: "Le \"roulis\" désigne une rotation de l'avion autour de son axe :", options: ["Longitudinal", "Vertical", "Transversal", "Diagonal"], answer: "Longitudinal" },
  { id: "a6", sub: "principes", prompt: "Le \"tangage\" désigne une rotation autour de l'axe :", options: ["Longitudinal", "Transversal", "Vertical", "Diagonal"], answer: "Transversal" },
  { id: "a7", sub: "principes", prompt: "Le \"lacet\" désigne une rotation autour de l'axe :", options: ["Longitudinal", "Transversal", "Vertical", "Horizontal"], answer: "Vertical" },
  { id: "a8", sub: "principes", prompt: "Quelle surface de commande contrôle le roulis ?", options: ["Les ailerons", "La gouverne de profondeur", "La gouverne de direction", "Les volets"], answer: "Les ailerons" },
  { id: "a9", sub: "principes", prompt: "Quelle surface de commande contrôle le tangage ?", options: ["Les ailerons", "La gouverne de profondeur", "La gouverne de direction", "Le spoiler"], answer: "La gouverne de profondeur" },
  { id: "a10", sub: "principes", prompt: "Quelle surface de commande contrôle le lacet ?", options: ["Les ailerons", "La gouverne de profondeur", "La gouverne de direction", "Les volets"], answer: "La gouverne de direction" },
  { id: "a11", sub: "réglementation", prompt: "Le code \"IFR\" signifie :", options: ["Instrument Flight Rules", "International Flight Regulation", "Immediate Flight Response", "Interior Flight Route"], answer: "Instrument Flight Rules" },
  { id: "a12", sub: "réglementation", prompt: "Le code \"VFR\" signifie :", options: ["Visual Flight Rules", "Variable Flight Range", "Vertical Flight Reference", "Verified Flight Report"], answer: "Visual Flight Rules" },
  { id: "a13", sub: "général", prompt: "À quelle altitude approximative vole un avion de ligne en croisière ?", options: ["1 000 - 2 000 m", "3 000 - 4 000 m", "9 000 - 12 000 m", "20 000 - 25 000 m"], answer: "9 000 - 12 000 m" },
  { id: "a14", sub: "général", prompt: "Que signifie \"Mach 1\" ?", options: ["La vitesse du son", "La vitesse de décrochage", "L'altitude maximale", "La vitesse de croisière standard"], answer: "La vitesse du son" },
  { id: "a15", sub: "principes", prompt: "Le \"décrochage\" (stall) survient quand :", options: ["L'angle d'incidence dépasse l'angle critique et la portance chute", "Les moteurs s'arrêtent", "L'avion dépasse Mach 1", "Le train d'atterrissage se bloque"], answer: "L'angle d'incidence dépasse l'angle critique et la portance chute" },
  { id: "a16", sub: "général", prompt: "La boîte noire enregistre principalement :", options: ["Les données de vol et les conversations du cockpit", "La météo", "Les bagages", "La consommation de carburant uniquement"], answer: "Les données de vol et les conversations du cockpit" },
  { id: "a17", sub: "réglementation", prompt: "Que signifie \"ETOPS\" pour un bimoteur ?", options: ["Autorisation de vol prolongé au-dessus de l'eau en cas de panne moteur", "Un type de radar", "Une norme de carburant", "Un protocole de communication"], answer: "Autorisation de vol prolongé au-dessus de l'eau en cas de panne moteur" },
  { id: "a18", sub: "général", prompt: "Le \"point de non-retour\" (PNR) désigne :", options: ["Le point après lequel il est plus économique de continuer que de faire demi-tour", "Le point de décrochage", "L'altitude de croisière", "Le seuil de piste"], answer: "Le point après lequel il est plus économique de continuer que de faire demi-tour" },
  { id: "a19", sub: "général", prompt: "Qu'est-ce que le \"givrage\" en vol ?", options: ["L'accumulation de glace sur les surfaces de l'avion", "Un problème électrique", "Une panne de radar", "Une surchauffe moteur"], answer: "L'accumulation de glace sur les surfaces de l'avion" },
  { id: "a20", sub: "général", prompt: "La check-list \"avant décollage\" sert notamment à :", options: ["Vérifier systématiquement les paramètres critiques de l'appareil", "Calculer le prix du billet", "Enregistrer les passagers", "Programmer le pilote automatique uniquement"], answer: "Vérifier systématiquement les paramètres critiques de l'appareil" },
  { id: "a21", sub: "général", prompt: "\"CDG\" en région parisienne est le code IATA de :", options: ["Orly", "Charles de Gaulle", "Le Bourget", "Beauvais"], answer: "Charles de Gaulle" },
  { id: "a22", sub: "général", prompt: "Que veut dire \"hub\" pour une compagnie aérienne ?", options: ["Un aéroport de correspondance central", "Un type d'avion", "Une classe tarifaire", "Un simulateur de vol"], answer: "Un aéroport de correspondance central" },
  { id: "a23", sub: "instruments", prompt: "Le \"QNH\" est un réglage altimétrique correspondant à :", options: ["La pression atmosphérique ramenée au niveau de la mer", "La vitesse du vent", "La température extérieure", "L'humidité relative"], answer: "La pression atmosphérique ramenée au niveau de la mer" },
  { id: "a24", sub: "général", prompt: "Un \"winglet\" (bout d'aile relevé) sert à :", options: ["Réduire la traînée induite et améliorer l'efficacité", "Stocker du carburant", "Éclairer la piste", "Mesurer l'altitude"], answer: "Réduire la traînée induite et améliorer l'efficacité" },
  { id: "a25", sub: "principes", prompt: "La \"VMO/MMO\" représente :", options: ["La vitesse/le mach maximum autorisé en exploitation", "La vitesse minimale de décrochage", "La vitesse de croisière économique", "La vitesse au sol maximale"], answer: "La vitesse/le mach maximum autorisé en exploitation" },
  { id: "a26", sub: "général", prompt: "Un avion \"long-courrier\" est conçu pour :", options: ["Les vols domestiques courts", "Les vols intercontinentaux longue distance", "Le fret uniquement", "Les vols d'entraînement"], answer: "Les vols intercontinentaux longue distance" },
  { id: "a27", sub: "général", prompt: "L'\"APU\" (Auxiliary Power Unit) sert à :", options: ["Fournir de l'énergie électrique et pneumatique au sol ou en secours", "Propulser l'avion en croisière", "Refroidir la cabine uniquement", "Stocker le carburant de secours"], answer: "Fournir de l'énergie électrique et pneumatique au sol ou en secours" },
  { id: "a28", sub: "histoire", prompt: "Concorde était célèbre pour :", options: ["Être le premier avion de ligne supersonique commercial", "Être le premier avion tout composite", "Être le plus gros porteur du monde", "Voler sans pilote"], answer: "Être le premier avion de ligne supersonique commercial" },
  { id: "a29", sub: "général", prompt: "L'Airbus A320 et le Boeing 737 sont tous deux des avions :", options: ["Monocouloirs moyen-courriers", "Gros-porteurs long-courriers", "Cargos exclusivement", "Supersoniques"], answer: "Monocouloirs moyen-courriers" },
  { id: "a30", sub: "réglementation", prompt: "La \"piste\" d'un aéroport est numérotée en fonction :", options: ["De son orientation magnétique arrondie à la dizaine de degrés", "De sa longueur en mètres", "De l'ordre de construction", "Du nombre de vols quotidiens"], answer: "De son orientation magnétique arrondie à la dizaine de degrés" },
];

const BANKS = { verbal: VERBAL_BANK, anglais: ANGLAIS_BANK, aero: AERO_BANK };
